### Tensforflow With Metal Issue
It would appear that I have identified an issue with using tensorflow with metal in my mac computer.  I believe I fixed it.  I had to update my code to fix it.  It could possibly have just been a one time message like I am still currently getting.  I didn't record the message.  I'm still getting a one time message the first time I use tf, telling me about the status of the use of metal.
```bash
pip install tensorflow-macos tensorflow-metal --upgrade
```

### Example Code Page 76

In [2]:
import tensorflow as tf
import numpy as np

# tf will not let you change the value of an element in the array
x = tf.ones(shape=(2, 2))
# x[0,0] = 0 doesn't work, gives an error
print("tf ones", x)

# numpy allows you to change the value of an element in the array
x1 = np.ones(shape=(2, 2))
x1[0,0] = 0

print("np ones", x1)
y = tf.zeros(shape=(2, 1))
print(y)

z = tf.random.normal(shape=(2, 1), mean=0., stddev=1.)
print(z)

tf ones tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
np ones [[0. 1.]
 [1. 1.]]
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[-1.1725018 ]
 [-0.01549974]], shape=(2, 1), dtype=float32)


2024-09-08 19:02:55.703803: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2 Max
2024-09-08 19:02:55.703821: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 32.00 GB
2024-09-08 19:02:55.703827: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 10.67 GB
2024-09-08 19:02:55.703846: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-08 19:02:55.703858: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


### Example Code From 77

In [3]:
import tensorflow as tf
# This is an acceptable to way reassign the value of a variable
# in tensorflow
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

v.assign(tf.ones((3, 1)))

# This doesn't actually work because it's not supported in metal, but otherwise it should work.
# v[0, 0].assign(3.)

v.assign_add(tf.ones((3, 1)))

print(v)


<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.3544159 ],
       [ 0.7045493 ],
       [ 0.03666191]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[2.],
       [2.],
       [2.]], dtype=float32)>


### Examples Page 78

In [4]:
import tensorflow as tf
a = tf.ones((2, 2))
print(a)
b = tf.square(a)
print(b)
c = tf.sqrt(a)
print(c)
d = b + c
print(d)
# take the product of the two tensors
e = tf.matmul(a, b)
print(e)
# multiplication is element-wise
e *= d

print(e)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


### 3.5.3

In [5]:
#3.11
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
  result = tf.square(input_var)
  print(result)
print(input_var)

tf.Tensor(9.0, shape=(), dtype=float32)
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>


In [8]:
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
  tape.watch(input_const)
  result = tf.square(input_const)
  print(result)
grandient = tape.gradient(result, input_const)
print(grandient)
print(tape)

tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)
