### Tensforflow With Metal Issue
It would appear that I have identified an issue with using tensorflow with metal in my mac computer.  I had to update my code to fix it.
```bash
pip install tensorflow-macos tensorflow-metal --upgrade
```

### Example Code Page 76

In [9]:
import tensorflow as tf
import numpy as np

# tf will not let you change the value of an element in the array
x = tf.ones(shape=(2, 2))
# x[0,0] = 0 doesn't work, gives an error
print("tf ones", x)

# numpy allows you to change the value of an element in the array
x1 = np.ones(shape=(2, 2))
x1[0,0] = 0

print("np ones", x1)
y = tf.zeros(shape=(2, 1))
print(y)

z = tf.random.normal(shape=(2, 1), mean=0., stddev=1.)
print(z)

tf ones tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
np ones [[0. 1.]
 [1. 1.]]
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[-1.3544159]
 [ 0.7045493]], shape=(2, 1), dtype=float32)


### Example Code From 77

In [11]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

v.assign

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.3544159 ],
       [ 0.7045493 ],
       [ 0.03666191]], dtype=float32)>
